# Generated by Django 5.0.4 on 2024-04-25 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.FileField(upload_to='articles/%Y/%m/%d/'),
        ),
    ]
