# Generated by Django 5.0.4 on 2024-05-28 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_alter_article_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pdf_file',
            field=models.FileField(default='default.pdf', upload_to='articles/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.FileField(default='default.html', upload_to='articles/'),
        ),
    ]
