# Generated by Django 5.0.4 on 2024-06-27 11:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_alter_article_pdf_file_alter_article_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='article',
            old_name='original_url',
            new_name='original_article_url',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='user',
            new_name='publisher',
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.CharField(db_default='df_author', max_length=255),
        ),
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('DF', 'Draft'), ('PB', 'Published')], default='DF', max_length=2),
        ),
        migrations.AlterField(
            model_name='article',
            name='pdf_file',
            field=models.FileField(db_default='df_pdf', upload_to='articles/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(db_default='df_slug', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(db_default='df_title', max_length=255),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['-created_at'], name='articles_ar_created_312397_idx'),
        ),
    ]
