# Generated by Django 5.0.4 on 2024-06-27 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_alter_article_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(default='df_author', max_length=255),
        ),
        migrations.AlterField(
            model_name='article',
            name='pdf_file',
            field=models.FileField(default='df_pdf', upload_to='articles/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(default='df_title', max_length=255),
        ),
    ]
