# Generated by Django 5.0.4 on 2024-06-28 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_alter_article_author_alter_article_pdf_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='status',
        ),
    ]
